# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 271f65b365f8a640346f296ec8fc60f34541c59ceeb87865159fb7a9b14f9dc72786f9931d1117a2d9656b7adb8d0890a25cc98c22de14a3b71c1a42376e019d

test:
  secret_key_base: 2cb4232ae6506992f26d000089e15c4a5c6a7fd306072c62f7a20bae3ef56691716ac0997556811a63d690b1fdf2e466dfb12f6f38e3950c3461596978753da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
